name = "verbose"
defaultTargets = ["Verbose"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
pp.proofs.withType = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.25.0"

[[lean_lib]]
name = "Verbose"
globs = ["Verbose.*"]
